// GENERATED by the Chronicler backend — do not edit by hand.
// Regenerate: cargo run --manifest-path backend/Cargo.toml --bin gen-bindings
// (`cargo test` fails while this file is stale.)
/* eslint-disable */

export type AddAliasParams = { id: number, alias: string, };

/**
 * Partial update: omitted fields keep their current values. Settings are
 * app-wide (every book).
 */
export type AiConfigSetParams = { provider?: Provider, 
/**
 * Required for openai-compat; optional override for openrouter.
 */
baseUrl?: string, 
/**
 * High-volume extraction (facts, names, synopses).
 */
fastModel?: string, 
/**
 * Judgement (continuity, critique, voice, conversation).
 */
deepModel?: string, 
/**
 * Embeddings model for passage search ("" = provider default).
 */
embedModel?: string, 
/**
 * Task key → model id; replaces the whole map.
 */
overrides?: { [key in string]: string }, discovery?: boolean, ledgerOnSave?: boolean, liveContinuity?: boolean, 
/**
 * Added to the conversation prompt.
 */
chatInstructions?: string, 
/**
 * Replaces the built-in conversation prompt ("" = back to built-in).
 */
chatPrompt?: string, };

export type AiConfigView = { provider: Provider, baseUrl: string, fastModel: string, deepModel: string, embedModel: string, 
/**
 * Task key → model id.
 */
overrides: { [key in string]: string }, discovery: boolean, ledgerOnSave: boolean, liveContinuity: boolean, 
/**
 * Added to the conversation prompt.
 */
chatInstructions: string, 
/**
 * Replaces the built-in conversation prompt ("" = built-in).
 */
chatPrompt: string, hasKey: boolean, };

export type AiScanResult = { newCandidates: number, aliasesAdded: number, };

/**
 * Where a candidate was seen.
 */
export type CandidateContext = { file: string, line: number, text: string, };

export type CandidateList = { candidates: Array<CandidateRow>, };

export type CandidateRow = { name: string, kindGuess: string, 
/**
 * Number of files the name was seen in.
 */
count: number, files: Array<string>, contexts: Array<CandidateContext>, source: string, summary: string, };

export type CatchUp = { file: string, 
/**
 * The chapter (folder path, " › "-joined; "" for a loose scene).
 */
chapter: string, 
/**
 * 1-based position in reading order, and the number of scenes.
 */
position: number, total: number, 
/**
 * The model's "story so far" ("" unless `summary` is "ready").
 */
storySoFar: string, 
/**
 * ready | pending (ask again with `summary: true`) | no_ai | failed
 */
summary: string, 
/**
 * Why the summary failed, when it did.
 */
summaryError: string, 
/**
 * Scenes up to here with neither a synopsis nor noted facts, so the
 * summary had little to go on for them.
 */
missingSynopses: number, leftOff: LeftOff, 
/**
 * Plot threads running through this chapter.
 */
threads: Array<CatchUpThread>, 
/**
 * Margin notes still in this chapter's scenes.
 */
notes: Array<Note>, lastWorked: LastWorked, };

export type CatchUpParams = { path: string, 
/**
 * Write the story so far if it isn't cached (an AI call). Default true;
 * false returns the factual parts at once (and a cached summary).
 */
summary?: boolean, 
/**
 * Ignore a cached summary and write a fresh one.
 */
refresh?: boolean, };

export type CatchUpThread = { id: number, name: string, color: string, 
/**
 * This chapter's scenes it runs through, in reading order.
 */
scenes: Array<string>, 
/**
 * The latest scene up to and including this one that carries it.
 */
lastSeen: string | null, };

/**
 * One change (a locked-in version, or the working draft).
 */
export type Change = { changeId: string, commitId: string, parentId: string, 
/**
 * The working draft.
 */
current: boolean, empty: boolean, 
/**
 * Unix seconds.
 */
created: number, updated: number, files: Array<string>, description: string, };

export type ChangeIdParams = { changeId: string, };

export type ChangeList = { changes: Array<Change>, };

export type ChapterSpec = { title: string, 
/**
 * Project-relative scene file paths, in order. The RPC layer reads them
 * (path-confined) and hands contents to `run`.
 */
scenes: Array<string>, };

export type ChatMessage = { role: Role, content: string, };

export type ChatParams = { 
/**
 * Run id, for `agents/stop` and event tagging. Default "rig".
 */
id?: string, 
/**
 * The conversation; the last message is the live prompt and must be
 * from the user.
 */
messages: Array<ChatMessage>, 
/**
 * The currently open scene's text.
 */
context?: string, 
/**
 * Files the writer attached explicitly.
 */
attach?: Array<string>, };

export type ChatResult = { text: string, stopped: boolean, };

/**
 * Two entities appearing in the same scene(s).
 */
export type CoEdge = { a: number, b: number, 
/**
 * Number of scenes shared.
 */
weight: number, };

export type CodexSuggestParams = { name: string, 
/**
 * Where the selection was made.
 */
file?: string, context?: string, 
/**
 * 1-based.
 */
line?: number, };

export type CodexSuggestResult = { 
/**
 * False when the name was already known, dismissed, or queued.
 */
added: boolean, };

export type CompileParams = { settings: CompileSettings, chapters: Array<ChapterSpec>, 
/**
 * Front Matter files, in order.
 */
frontMatter?: Array<string>, 
/**
 * Back Matter files, in order.
 */
backMatter?: Array<string>, };

export type CompileResult = { 
/**
 * Absolute path of the artifact, inside `.chronicler/build/`.
 */
output: string, };

export type CompileSettings = { title?: string, author?: string, paper?: string, fontSize?: number, fontFamily?: string, lineSpacing?: number, justify?: boolean, firstLineIndent?: boolean, titlePage?: boolean, chapterPageBreaks?: boolean, numbering?: boolean, sceneSeparator?: string, customPreamble?: string, 
/**
 * pdf | typst | markdown
 */
format?: string, 
/**
 * Aesthetic preset: modern-novel | classic-manuscript | elegant-book | plain
 */
template?: string, };

export type ContinuityResult = { 
/**
 * Contradictions standing (in the checked scope).
 */
findings: number, 
/**
 * Scenes checked this run.
 */
checked: number, 
/**
 * Scenes skipped because nothing they depend on changed.
 */
unchanged: number, 
/**
 * Scenes the AI provider failed on.
 */
failed: number, summary: string, stopped: boolean, };

export type CritiqueBrief = { audience?: string, tone?: string, similarAuthors?: string, style?: string, notes?: string, };

export type CritiqueParams = { brief?: CritiqueBrief, };

export type CritiqueResult = { problems: number, markdown: string, };

export type CrutchWord = { word: string, count: number, 
/**
 * Uses per 10,000 words.
 */
per10k: number, };

export type DayWords = { 
/**
 * The client's local date, e.g. "2026-08-25".
 */
date: string, 
/**
 * Words added that day (can be negative).
 */
written: number, };

export type DefaultPrompts = { 
/**
 * The built-in conversation prompt.
 */
chat: string, };

export type DescribeParams = { changeId: string, message: string, };

export type DiagFiles = { 
/**
 * Diagnostics per project-relative file.
 */
files: { [key in string]: Array<Diagnostic> }, };

export type DiagSource = "spelling" | "grammar" | "style" | "assistant";

export type DiagStatus = { 
/**
 * The language engine is loaded (checks are fast).
 */
ready: boolean, };

/**
 * One problem in one scene. Positions are 1-based lines and 0-based
 * character (not byte) columns, end exclusive.
 */
export type Diagnostic = { source: DiagSource, severity: Severity, file: string, line: number, colStart: number, colEnd: number, 
/**
 * The flagged text.
 */
text: string, message: string, 
/**
 * Stable rule key, used by `diag/ignore`.
 */
ruleId: string, 
/**
 * Ready-made fixes. Always empty for spelling — ask `diag/suggest`.
 */
replacements: Array<string>, 
/**
 * Set for assistant findings (`agents/finding_dismiss`).
 */
findingId?: number, };

export type Dialect = "american" | "british" | "australian" | "canadian" | "indian";

export type DialectValue = { dialect: Dialect, };

export type Diff = { files: Array<FileDiff>, };

export type DiffParams = { from: string, to: string, 
/**
 * One file; omit for every changed file.
 */
path?: string, };

export type DocumentContent = { content: string, };

export type DraftedResult = { drafted: number, };

export type Entity = { id: number, name: string, 
/**
 * character | place | item | faction | creature | event | lore
 */
kind: string, summary: string, body: string, aliases: Array<string>, 
/**
 * Unix seconds.
 */
updated: number, mentionCount: number, };

export type EntityCreateParams = { name: string, 
/**
 * Default "character".
 */
kind?: string, summary?: string, aliases?: Array<string>, };

export type EntityList = { entities: Array<Entity>, };

export type EntityUpdateParams = { id: number, name?: string, kind?: string, summary?: string, body?: string, aliases?: Array<string>, };

/**
 * What a whole-book job will read, and roughly what it costs.
 */
export type Estimate = { 
/**
 * Scenes the job will actually send (unchanged ones are skipped).
 */
scenes: number, words: number, inputTokens: number, outputTokens: number, model: string, 
/**
 * USD, when the provider publishes prices for the model.
 */
cost?: number, };

/**
 * Jobs that read the whole book and are worth pricing before they run.
 */
export type EstimateJob = "continuity" | "ledger" | "critique" | "synopses";

export type EstimateParams = { job: EstimateJob, };

export type Evolog = { entries: Array<EvologEntry>, };

/**
 * One save inside a change.
 */
export type EvologEntry = { commitId: string, predecessorId: string, timestamp: number, files: Array<string>, };

export type FactsParams = { 
/**
 * Name or keyword filter.
 */
subject?: string, };

export type FileDiff = { 
/**
 * jj's status: added | removed | modified | renamed | copied
 */
status: string, path: string, oldPath: string, binary: boolean, wordsAdded: number, wordsRemoved: number, paragraphs: Array<Paragraph>, };

/**
 * One binder entry.
 */
export type FileEntry = { 
/**
 * Project-relative path, forward slashes.
 */
path: string, isDir: boolean, };

export type FileList = { 
/**
 * Folders first, then files, each alphabetical by path.
 */
files: Array<FileEntry>, };

export type FileWords = { file: string, words: number, };

export type FillField = "summary" | "body";

export type FillParams = { 
/**
 * Entity id.
 */
id: number, field: FillField, };

export type FixParams = { path: string, 
/**
 * 1-based.
 */
line: number, 
/**
 * 0-based character column, inclusive.
 */
colStart: number, 
/**
 * 0-based character column, exclusive.
 */
colEnd: number, 
/**
 * The text the diagnostic saw; the fix is refused if it changed.
 */
text: string, replacement: string, };

export type Graph = { nodes: Array<GraphNode>, coEdges: Array<CoEdge>, relations: Array<Relation>, };

export type GraphNode = { id: number, name: string, kind: string, mentions: number, };

export type HygieneResult = { suggestions: number, summary: string, stopped: boolean, };

export type IdParams = { id: number, };

export type IdResult = { id: number, };

export type IgnoreParams = { ruleId: string, 
/**
 * The file to ignore it in; omit (or "*") for everywhere.
 */
file?: string, 
/**
 * The flagged text; omit to ignore the rule entirely.
 */
text?: string, };

/**
 * One thing the writer told the checker to ignore.
 */
export type Ignored = { ruleId: string, 
/**
 * A scene path, or "*" for everywhere.
 */
file: string, 
/**
 * The ignored text ("" = the whole rule).
 */
text: string, };

export type IgnoredList = { ignored: Array<IgnoredView>, };

export type IgnoredView = { ruleId: string, file: string, text: string, 
/**
 * The rule in plain words ("Repeated word", "Spelling").
 */
label: string, };

export type IndexResult = { files: number, chunks: number, };

export type IndexStatus = { indexedFiles: number, chunks: number, 
/**
 * Empty when no embedding model is configured.
 */
embedModel: string, 
/**
 * The index was built with the configured model.
 */
currentModel: boolean, };

export type JournalClearParams = { 
/**
 * Omit to clear every entry.
 */
path?: string, };

export type JournalEntries = { 
/**
 * Oldest first.
 */
entries: Array<JournalEntry>, };

export type JournalEntry = { path: string, content: string, 
/**
 * Unix milliseconds.
 */
savedAt: number, };

export type JournalWriteParams = { path: string, 
/**
 * The unsaved buffer.
 */
content: string, };

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type KeyParams = { 
/**
 * Empty clears the key.
 */
key: string, };

export type KnownEntity = { id: number, name: string, kind: string, 
/**
 * Latest first.
 */
facts: Array<KnownFact>, };

/**
 * One thing the reader has been told, and where.
 */
export type KnownFact = { fact: string, 
/**
 * The scene that established it.
 */
scene: string, 
/**
 * "narrated" or "claimed" (a character's word, possibly false).
 */
basis: string, };

export type LastWorked = { 
/**
 * When this scene was last changed (Unix ms; saved or unsaved).
 */
sceneAt: number | null, 
/**
 * The scene most recently changed anywhere in the book, and when.
 */
latestScene: string | null, latestAt: number | null, 
/**
 * The last day with words written (the writer's local date).
 */
lastDay: string | null, lastDayWords: number, };

export type LedgerParams = { 
/**
 * Re-extract every scene, not just changed ones.
 */
force?: boolean, };

export type LedgerResult = { 
/**
 * Scenes (re)read.
 */
scenes: number, 
/**
 * Facts in the ledger.
 */
facts: number, 
/**
 * Scenes the AI provider failed on.
 */
failed: number, };

/**
 * Where the text of the current scene stops.
 */
export type LeftOff = { 
/**
 * The scene's last paragraph(s), verbatim (margin notes removed).
 */
excerpt: string, 
/**
 * 1-based lines the excerpt spans.
 */
line: number, endLine: number, words: number, 
/**
 * Word target (0 = none).
 */
target: number, status: string, synopsis: string, pov: string | null, location: string | null, storyTime: string, 
/**
 * The scene has edits not yet saved (read from the journal).
 */
unsaved: boolean, };

export type LinksResult = { links: number, };

export type LockIn = { locked: boolean, reason?: string, };

export type LockInParams = { 
/**
 * The name for the locked-in change (required).
 */
message: string, };

export type Markdown = { markdown: string, };

export type Mention = { file: string, 
/**
 * 1-based.
 */
line: number, };

export type MentionList = { mentions: Array<Mention>, };

export type MergeResult = { 
/**
 * The scene that was folded in (now gone).
 */
merged: string, };

/**
 * Partial update of a scene's details: omitted fields keep their values.
 */
export type MetaSetParams = { path: string, synopsis?: string, 
/**
 * idea | draft | revised | final | ""
 */
status?: string, 
/**
 * Codex entity id for the point-of-view character; 0 clears.
 */
pov?: number, 
/**
 * Codex entity id for the location; 0 clears.
 */
location?: number, storyTime?: string, 
/**
 * Word target; 0 clears.
 */
target?: number, 
/**
 * Plot thread ids (replaces the scene's set).
 */
threads?: Array<number>, };

/**
 * A model the provider offers, with what it costs when the provider says.
 */
export type ModelInfo = { id: string, name?: string, contextLength?: number, 
/**
 * USD per million input tokens.
 */
inputPrice?: number, 
/**
 * USD per million output tokens.
 */
outputPrice?: number, };

export type ModelList = { models: Array<ModelInfo>, };

export type NameParams = { name: string, };

export type NerStatus = { 
/**
 * The model is downloaded.
 */
ready: boolean, 
/**
 * The model is in memory right now.
 */
loaded: boolean, modelDir: string, };

/**
 * Params for methods that take none (`{}` or `null` on the wire).
 */
export type NoParams = Record<symbol, never>;

export type Note = { file: string, 
/**
 * 1-based line where the note starts.
 */
line: number, 
/**
 * The note, without the comment markers.
 */
text: string, };

export type NoteList = { notes: Array<Note>, };

export type NoteResolveParams = { path: string, 
/**
 * 1-based line the note starts on (as listed).
 */
line: number, 
/**
 * The note's text (as listed), to find it even if lines shifted.
 */
text: string, };

export type OptionalPathParams = { 
/**
 * One file; omit for the whole project.
 */
path?: string, };

export type OverusedWord = { word: string, count: number, per10k: number, 
/**
 * Up to five places it's used.
 */
examples: Array<WordExample>, };

/**
 * A paragraph of a prose diff: `segments` are `[tag, text]` pairs.
 */
export type Paragraph = { tag: ParagraphTag, segments: Array<[SegmentTag, string]>, };

export type ParagraphTag = "equal" | "insert" | "delete" | "modify";

export type PathParams = { 
/**
 * Project-relative path.
 */
path: string, };

export type ProjectStats = { total: number, files: Array<FileWords>, today: DayWords, 
/**
 * The last 14 writing days, newest first.
 */
history: Array<DayWords>, };

export type PromoteParams = { name: string, 
/**
 * For a new entity; default "character".
 */
kind?: string, summary?: string, 
/**
 * Add the name as an alias of this entity instead.
 */
asAliasOf?: number, };

/**
 * The outcome of promoting a candidate.
 */
export type Promoted = { "created": number } | { "aliasedTo": number };

export type ProseReport = { 
/**
 * Words of prose in the manuscript (headings, notes and matter excluded).
 */
words: number, 
/**
 * Common crutch words and phrases that appear, most frequent first.
 */
crutch: Array<CrutchWord>, 
/**
 * The writer's own most-repeated distinctive words, most frequent first.
 */
overused: Array<OverusedWord>, 
/**
 * Sentence rhythm per scene, in reading order.
 */
scenes: Array<SceneRhythm>, };

export type Provider = "openrouter" | "openai-compat";

export type ReaderKnowledge = { 
/**
 * Codex entries the reader meets for the first time here.
 */
introduced: Array<KnownEntity>, 
/**
 * Entries in this scene the reader already knows, with what they know.
 */
known: Array<KnownEntity>, 
/**
 * Scenes before this one whose facts haven't been noted yet (so the
 * picture may be incomplete).
 */
unreadScenes: number, };

export type Ready = { ready: boolean, };

export type RebuildResult = { mentions: number, candidates: number, files: number, };

export type ReindexResult = { mentions: number, };

export type Relation = { id: number, from: number, to: number, label: string, 
/**
 * human | llm
 */
source: string, };

export type RelationAddParams = { from: number, to: number, label: string, };

export type RenameApplyParams = { id: number, from: string, to: string, 
/**
 * Occurrences to rewrite; omit or leave empty to rename in the codex only.
 */
chosen?: Array<RenameChoice>, 
/**
 * Keep the old name as another name for the entry.
 */
keepAlias?: boolean, 
/**
 * Also rewrite codex entries and scene synopses.
 */
updateNotes?: boolean, };

export type RenameChoice = { path: string, 
/**
 * `start` offsets from the preview.
 */
starts: Array<number>, };

/**
 * Codex text or a scene synopsis that mentions the old name.
 */
export type RenameNote = { 
/**
 * entry | synopsis
 */
kind: string, 
/**
 * The codex entry's name, or the scene's path.
 */
name: string, count: number, };

export type RenameOccurrence = { 
/**
 * Byte offset in the file; send it back to choose this occurrence.
 */
start: number, 
/**
 * 1-based.
 */
line: number, 
/**
 * 0-based, in UTF-16 units (editor columns).
 */
column: number, 
/**
 * The text as written ("Maren", "MAREN", "Marens").
 */
found: string, replacement: string, 
/**
 * The rest of the line around it, trimmed to a readable snippet.
 */
before: string, after: string, };

export type RenameParams = { from: string, to: string, };

export type RenamePreview = { 
/**
 * Scenes in reading order (front and back matter last).
 */
scenes: Array<RenameScene>, total: number, notes: Array<RenameNote>, };

export type RenamePreviewParams = { id: number, 
/**
 * The entry's current name, or one of its other names.
 */
from: string, to: string, };

export type RenameResult = { filesChanged: number, replaced: number, notesChanged: number, };

export type RenameScene = { path: string, occurrences: Array<RenameOccurrence>, };

export type ReplaceParams = { query: string, replacement: string, matchCase?: boolean, 
/**
 * Limit to one file…
 */
file?: string, 
/**
 * …and optionally one 1-based line in it.
 */
line?: number, };

export type ReplaceResult = { filesChanged: number, occurrences: number, };

export type ResearchClipParams = { 
/**
 * An http(s) address.
 */
url: string, };

export type ResearchClipResult = { 
/**
 * `Research/Clippings/<title>.md`.
 */
path: string, title: string, };

/**
 * One file in the research folder.
 */
export type ResearchItem = { 
/**
 * Project-relative path, e.g. `Research/Clippings/Tides.md`.
 */
path: string, 
/**
 * File name, without `.md` for notes and clippings.
 */
name: string, kind: ResearchKind, 
/**
 * Bytes.
 */
size: number, 
/**
 * Last modified, milliseconds since the Unix epoch.
 */
modified: number, 
/**
 * The page a clipping came from.
 */
source?: string, };

export type ResearchKind = "note" | "clipping" | "image" | "pdf" | "other";

export type ResearchList = { 
/**
 * Notes, clippings, images, PDFs, other — each by name.
 */
items: Array<ResearchItem>, };

export type ResearchNoteParams = { 
/**
 * The note's title; also its file name (made unique).
 */
name: string, };

export type ResearchPath = { 
/**
 * Project-relative path of the new file.
 */
path: string, };

export type ResearchText = { text: string, };

export type RestoreParams = { 
/**
 * A change id, commit id, or "@".
 */
rev: string, 
/**
 * One file; omit to restore the whole project.
 */
path?: string, };

export type Role = "user" | "assistant";

export type RpcEvent = { "method": "project/changed", "params": { paths: Array<string>, } } | { "method": "history/changed", "params": Record<symbol, never> } | { "method": "diag/updated", "params": { files: { [key in string]: Array<Diagnostic> }, } } | { "method": "diag/ready", "params": Record<symbol, never> } | { "method": "codex/changed", "params": { newCandidates: number, } } | { "method": "agents/delta", "params": { id: string, text: string, } } | { "method": "agents/tool", "params": { id: string, name: string, args: JsonValue, } } | { "method": "agents/tool_done", "params": { id: string, name: string, } } | { "method": "agents/error", "params": { id: string, message: string, } } | { "method": "agents/sweep", "params": { job: string, note: string, } } | { "method": "agents/finding", "params": { file: string, } } | { "method": "system/recompiling", "params": Record<symbol, never> };

export type SaveParams = { path: string, content: string, };

export type ScanResult = { newCandidates: number, scanned: number, };

/**
 * Everything about a scene that isn't its text.
 */
export type SceneDetails = { file: string, synopsis: string, 
/**
 * idea | draft | revised | final | ""
 */
status: string, 
/**
 * Codex entity whose point of view the scene is in.
 */
pov: number | null, 
/**
 * Codex entity (a place) where it happens.
 */
location: number | null, 
/**
 * When it happens in the story, in the writer's words ("Day 3, dusk").
 */
storyTime: string, 
/**
 * Word target (0 = none).
 */
target: number, 
/**
 * Plot thread ids.
 */
threads: Array<number>, };

export type SceneMetaList = { meta: Array<SceneDetails>, };

export type SceneRhythm = { file: string, sentences: number, 
/**
 * Mean words per sentence.
 */
avgLength: number, 
/**
 * Standard deviation of words per sentence (higher = more varied).
 */
stdev: number, };

export type SearchHit = { file: string, 
/**
 * 1-based.
 */
line: number, 
/**
 * The trimmed line, at most 200 characters.
 */
text: string, };

export type SearchParams = { query: string, 
/**
 * Default false.
 */
matchCase?: boolean, };

export type SearchResults = { 
/**
 * At most 200.
 */
results: Array<SearchHit>, };

export type SegmentTag = "equal" | "insert" | "delete";

export type SettingGetParams = { key: string, };

export type SettingSetParams = { key: string, value: string, };

export type SettingValue = { value: string | null, };

export type Severity = "error" | "warning" | "info";

export type SpeakParams = { 
/**
 * Plain text (markdown already stripped), ideally one paragraph.
 */
text: string, 
/**
 * A voice other than the configured one (previews).
 */
voice?: string, };

export type SpeakResult = { 
/**
 * Base64-encoded audio.
 */
audio: string, 
/**
 * Its type: audio/mpeg or audio/wav.
 */
mime: string, 
/**
 * Characters read.
 */
chars: number, 
/**
 * Served from the project's cache (no provider call, no cost).
 */
cached: boolean, };

/**
 * A speech model and the voices it offers.
 */
export type SpeechModel = { voices: Array<string>, id: string, name?: string, contextLength?: number, 
/**
 * USD per million input tokens.
 */
inputPrice?: number, 
/**
 * USD per million output tokens.
 */
outputPrice?: number, };

export type SpeechModelList = { models: Array<SpeechModel>, };

export type SpellSuggestParams = { word: string, };

export type SplitParams = { path: string, 
/**
 * What stays in this scene.
 */
before: string, 
/**
 * What becomes the new scene, placed right after it.
 */
after: string, 
/**
 * The new scene's name (without .md); omitted, "<this scene> (2)".
 */
name?: string, };

export type SplitResult = { 
/**
 * The new scene.
 */
path: string, };

export type StatsParams = { 
/**
 * The client's local date, e.g. "2026-08-25".
 */
today: string, };

export type StopParams = { 
/**
 * A chat id, or a job: continuity | ledger | timeline | relations |
 * synopses | hygiene | critique.
 */
id: string, };

export type Stopped = { 
/**
 * Whether anything was running under that id.
 */
stopped: boolean, };

/**
 * The persisted story timeline.
 */
export type StoredTimeline = { 
/**
 * Unix seconds.
 */
builtAt: number, 
/**
 * Story-chronological.
 */
events: Array<TimelineEvent>, };

/**
 * Which local style checks run, per project. Missing fields default on.
 */
export type StyleChecks = { 
/**
 * The same distinctive word again within a few lines.
 */
echoes: boolean, 
/**
 * "said softly": an -ly adverb on a dialogue tag.
 */
adverbTags: boolean, 
/**
 * Runs of sentences that are all about the same length.
 */
rhythm: boolean, 
/**
 * Filter words from the `styleWords` list.
 */
filterWords: boolean, };

/**
 * Turn individual style checks on or off; omitted fields keep their value.
 */
export type StyleChecksPatch = { echoes?: boolean, adverbTags?: boolean, rhythm?: boolean, filterWords?: boolean, };

export type Suggestions = { 
/**
 * Best first, at most 5, in the project's dialect.
 */
suggestions: Array<string>, };

export type SystemInfo = { version: string, status: string, 
/**
 * Absolute project root.
 */
root: string, };

/**
 * Replies from each model tier.
 */
export type TestResult = { fast: string, deep: string, };

export type TextResult = { text: string, };

export type Thread = { id: number, name: string, 
/**
 * A token name (e.g. "accent", "ai") or "" for the default.
 */
color: string, position: number, };

export type ThreadCreateParams = { name: string, 
/**
 * A colour token name; omit for the default.
 */
color?: string, };

export type ThreadList = { threads: Array<Thread>, };

export type ThreadUpdateParams = { id: number, name?: string, color?: string, position?: number, };

export type TimelineEvent = { 
/**
 * Short story-time label, e.g. "Years ago — the Siege", "Dawn, two days later".
 */
when: string, 
/**
 * One sentence: what happens.
 */
what: string, 
/**
 * Scene paths where this is established or shown.
 */
scenes: Array<string>, };

/**
 * Outside programs Chronicler relies on, with their versions; `None` when
 * not installed (or not on PATH).
 */
export type Tools = { 
/**
 * jj — version history.
 */
jj?: string, 
/**
 * typst — compiling the manuscript.
 */
typst?: string, };

/**
 * Partial update: omitted fields keep their values. Changing the model
 * clears the voice (voices belong to a model) unless one is given too.
 */
export type TtsConfigSetParams = { model?: string, voice?: string, speed?: number, };

export type TtsConfigView = { 
/**
 * The speech model in use ("" when the provider has no default and none was chosen).
 */
model: string, 
/**
 * The chosen voice ("" = the model's first).
 */
voice: string, 
/**
 * Narration speed (1.0 = natural).
 */
speed: number, };

/**
 * A voice the writer can pick.
 */
export type TtsVoice = { id: string, name: string, description?: string, 
/**
 * A short sample hosted by the provider.
 */
previewUrl?: string, };

export type TtsVoiceList = { voices: Array<TtsVoice>, };

export type WordExample = { file: string, 
/**
 * 1-based.
 */
line: number, };

export type WordList = { words: Array<string>, };

export type WordParams = { word: string, };

/** Every RPC method: `params` sent, `result` resolved. */
export interface Rpc {
  "ping": { params: NoParams; result: string };
  "system/info": { params: NoParams; result: SystemInfo };
  "system/tools": { params: NoParams; result: Tools };
  "db/get": { params: SettingGetParams; result: SettingValue };
  "db/set": { params: SettingSetParams; result: null };
  "stats/get": { params: StatsParams; result: ProjectStats };
  "document/read": { params: PathParams; result: DocumentContent };
  "document/save": { params: SaveParams; result: null };
  "project/list_files": { params: NoParams; result: FileList };
  "project/create_folder": { params: PathParams; result: null };
  "project/rename": { params: RenameParams; result: null };
  "project/delete": { params: PathParams; result: null };
  "project/search": { params: SearchParams; result: SearchResults };
  "project/replace": { params: ReplaceParams; result: ReplaceResult };
  "meta/get_all": { params: NoParams; result: SceneMetaList };
  "meta/set": { params: MetaSetParams; result: null };
  "threads/list": { params: NoParams; result: ThreadList };
  "threads/create": { params: ThreadCreateParams; result: IdResult };
  "threads/update": { params: ThreadUpdateParams; result: null };
  "threads/delete": { params: IdParams; result: null };
  "story/reader_knowledge": { params: PathParams; result: ReaderKnowledge };
  "notes/list": { params: NoParams; result: NoteList };
  "notes/resolve": { params: NoteResolveParams; result: null };
  "scene/split": { params: SplitParams; result: SplitResult };
  "scene/merge": { params: PathParams; result: MergeResult };
  "journal/write": { params: JournalWriteParams; result: null };
  "journal/read": { params: NoParams; result: JournalEntries };
  "journal/clear": { params: JournalClearParams; result: null };
  "codex/list": { params: NoParams; result: EntityList };
  "codex/create": { params: EntityCreateParams; result: IdResult };
  "codex/update": { params: EntityUpdateParams; result: null };
  "codex/delete": { params: IdParams; result: null };
  "codex/add_alias": { params: AddAliasParams; result: null };
  "codex/mentions": { params: IdParams; result: MentionList };
  "codex/candidates": { params: NoParams; result: CandidateList };
  "codex/dismiss": { params: NameParams; result: null };
  "codex/promote": { params: PromoteParams; result: Promoted };
  "codex/suggest": { params: CodexSuggestParams; result: CodexSuggestResult };
  "codex/reindex": { params: NoParams; result: ReindexResult };
  "codex/scan": { params: OptionalPathParams; result: ScanResult };
  "codex/graph": { params: NoParams; result: Graph };
  "codex/rename_preview": { params: RenamePreviewParams; result: RenamePreview };
  "codex/rename_apply": { params: RenameApplyParams; result: RenameResult };
  "index/rebuild": { params: NoParams; result: RebuildResult };
  "relations/add": { params: RelationAddParams; result: IdResult };
  "relations/delete": { params: IdParams; result: null };
  "diag/status": { params: NoParams; result: DiagStatus };
  "diag/check": { params: OptionalPathParams; result: DiagFiles };
  "diag/fix": { params: FixParams; result: null };
  "diag/suggest": { params: SpellSuggestParams; result: Suggestions };
  "diag/add_word": { params: WordParams; result: null };
  "diag/ignore": { params: IgnoreParams; result: null };
  "diag/dictionary": { params: NoParams; result: WordList };
  "diag/remove_word": { params: WordParams; result: null };
  "diag/ignored": { params: NoParams; result: IgnoredList };
  "diag/unignore": { params: Ignored; result: null };
  "diag/get_dialect": { params: NoParams; result: DialectValue };
  "diag/set_dialect": { params: DialectValue; result: null };
  "diag/style_get": { params: NoParams; result: StyleChecks };
  "diag/style_set": { params: StyleChecksPatch; result: StyleChecks };
  "diag/prose_report": { params: NoParams; result: ProseReport };
  "ner/status": { params: NoParams; result: NerStatus };
  "ner/ensure": { params: NoParams; result: Ready };
  "ai/config": { params: NoParams; result: AiConfigView };
  "ai/config_set": { params: AiConfigSetParams; result: null };
  "ai/set_key": { params: KeyParams; result: null };
  "ai/models": { params: NoParams; result: ModelList };
  "ai/test": { params: NoParams; result: TestResult };
  "ai/default_prompts": { params: NoParams; result: DefaultPrompts };
  "ai/scan": { params: PathParams; result: AiScanResult };
  "tts/config": { params: NoParams; result: TtsConfigView };
  "tts/config_set": { params: TtsConfigSetParams; result: null };
  "tts/models": { params: NoParams; result: SpeechModelList };
  "tts/voices": { params: NoParams; result: TtsVoiceList };
  "tts/speak": { params: SpeakParams; result: SpeakResult };
  "agents/chat": { params: ChatParams; result: ChatResult };
  "agents/stop": { params: StopParams; result: Stopped };
  "agents/continuity": { params: OptionalPathParams; result: ContinuityResult };
  "agents/finding_dismiss": { params: IdParams; result: null };
  "agents/ledger": { params: LedgerParams; result: LedgerResult };
  "agents/facts": { params: FactsParams; result: Markdown };
  "agents/timeline_build": { params: NoParams; result: StoredTimeline };
  "agents/timeline": { params: NoParams; result: StoredTimeline | null };
  "agents/relations_build": { params: NoParams; result: LinksResult };
  "agents/synopses": { params: NoParams; result: DraftedResult };
  "agents/hygiene": { params: NoParams; result: HygieneResult };
  "agents/voice": { params: IdParams; result: Markdown };
  "agents/critique": { params: CritiqueParams; result: CritiqueResult };
  "agents/fill": { params: FillParams; result: TextResult };
  "agents/index": { params: NoParams; result: IndexResult };
  "agents/status": { params: NoParams; result: IndexStatus };
  "agents/estimate": { params: EstimateParams; result: Estimate };
  "agents/catch_up": { params: CatchUpParams; result: CatchUp };
  "compile/run": { params: CompileParams; result: CompileResult };
  "research/list": { params: NoParams; result: ResearchList };
  "research/new_note": { params: ResearchNoteParams; result: ResearchPath };
  "research/clip": { params: ResearchClipParams; result: ResearchClipResult };
  "research/read": { params: PathParams; result: ResearchText };
  "history/changes": { params: OptionalPathParams; result: ChangeList };
  "history/evolog": { params: ChangeIdParams; result: Evolog };
  "history/describe": { params: DescribeParams; result: null };
  "history/lock_in": { params: LockInParams; result: LockIn };
  "history/restore": { params: RestoreParams; result: null };
  "history/diff": { params: DiffParams; result: Diff };
}

export type RpcMethod = keyof Rpc;
export type RpcParams<M extends RpcMethod> = Rpc[M]["params"];
export type RpcResult<M extends RpcMethod> = Rpc[M]["result"];
export type RpcEventMethod = RpcEvent["method"];
export type RpcEventParams<M extends RpcEventMethod> = Extract<RpcEvent, { method: M }>["params"];
