//! TypeScript bindings for the whole RPC surface, generated from the
//! method table. Regenerate with:
//!
//! ```sh
//! cargo run --manifest-path backend/Cargo.toml --bin gen-bindings
//! ```
//!
//! `cargo test` fails (test `bindings_are_current`) when the checked-in file
//! is stale.

use std::any::TypeId;
use std::collections::{BTreeMap, HashSet};
use ts_rs::{Config, TS, TypeVisitor};

pub const OUTPUT_PATH: &str = "../frontend/src/rpc.gen.ts";

pub struct Builder {
    cfg: Config,
    seen: HashSet<TypeId>,
    decls: BTreeMap<String, (String, String)>,
    methods: Vec<(String, String, String)>,
}

impl TypeVisitor for Builder {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        if !self.seen.insert(TypeId::of::<T>()) {
            return;
        }
        if T::output_path().is_some() {
            let ident = T::ident(&self.cfg);
            let mut decl = String::new();
            if let Some(docs) = T::docs() {
                decl.push_str(&docs);
            }
            decl.push_str("export ");
            decl.push_str(&T::decl(&self.cfg));
            let origin = std::any::type_name::<T>().to_string();
            if let Some((other, existing)) = self.decls.get(&ident) {
                // Shadow impls (serde_json::Value → JsonValue) share a decl.
                if *existing != decl {
                    panic!("two Rust types export as `{ident}`: {other} and {origin}");
                }
                return;
            }
            self.decls.insert(ident, (origin, decl));
        }
        T::visit_dependencies(self);
        T::visit_generics(self);
    }
}

impl Builder {
    pub fn method<P: TS + 'static, R: TS + 'static>(&mut self, name: &str) {
        self.visit::<P>();
        self.visit::<R>();
        self.methods
            .push((name.to_string(), P::name(&self.cfg), R::name(&self.cfg)));
    }
}

/// The complete contents of `rpc.gen.ts`.
pub fn typescript() -> String {
    let mut b = Builder {
        cfg: Config::new().with_large_int("number"),
        seen: HashSet::new(),
        decls: BTreeMap::new(),
        methods: Vec::new(),
    };
    super::describe(&mut b);
    b.visit::<crate::events::Event>();

    let mut out = String::from(
        "// GENERATED by the Chronicler backend — do not edit by hand.\n\
         // Regenerate: cargo run --manifest-path backend/Cargo.toml --bin gen-bindings\n\
         // (`cargo test` fails while this file is stale.)\n\
         /* eslint-disable */\n\n",
    );
    for (_, decl) in b.decls.values() {
        out.push_str(decl.trim_end());
        out.push_str("\n\n");
    }
    out.push_str(
        "/** Every RPC method: `params` sent, `result` resolved. */\nexport interface Rpc {\n",
    );
    for (name, params, result) in &b.methods {
        out.push_str(&format!(
            "  \"{name}\": {{ params: {params}; result: {result} }};\n"
        ));
    }
    out.push_str("}\n\n");
    out.push_str(
        "export type RpcMethod = keyof Rpc;\n\
         export type RpcParams<M extends RpcMethod> = Rpc[M][\"params\"];\n\
         export type RpcResult<M extends RpcMethod> = Rpc[M][\"result\"];\n\
         export type RpcEventMethod = RpcEvent[\"method\"];\n\
         export type RpcEventParams<M extends RpcEventMethod> = Extract<RpcEvent, { method: M }>[\"params\"];\n",
    );
    out
}

#[cfg(test)]
mod tests {
    #[test]
    fn bindings_are_current() {
        let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join(super::OUTPUT_PATH);
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        let fresh = super::typescript();
        assert!(
            current == fresh,
            "frontend/src/rpc.gen.ts is stale; run: cargo run --manifest-path backend/Cargo.toml --bin gen-bindings"
        );
    }
}
